version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    links:
      - auth

  auth:
    build:
      context: ./auth-server
    ports:
      - "3001:3001"
    volumes:
      - ./auth-server:/usr/src/app