version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - auth
    networks:
      - app-network

  auth:
    build:
      context: ./auth-server
    ports:
      - "3001:3001"
    volumes:
      - ./auth-server:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge